#!/usr/bin/env bash

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd)"
echo $DIR

ln -s "$DIR/.bash_profile" "$HOME/.bash_profile"
ln -s "$DIR/.gitconfig" "$HOME/.gitconfig"
ln -s "$DIR/.tmux.conf" "$HOME/.tmux.conf"
ln -s "$DIR/.rspec" "$HOME/.rspec"
ln -s "$DIR/.inputrc" "$HOME/.inputrc"
ln -s "$DIR/.vimrc" "$HOME/.vimrc"
